version: '3'

services:
  users_subs:
    image: marolok/users_subs:1.0.0
#    build:
#      context: .
#      dockerfile: Dockerfile
    environment:
      - APP_PROFILE=prod
      - DB_URL=jdbc:postgresql://pgsql:5432/postgres
      - DB_USR=postgres
      - DB_PWD=postgres
    tty: true
    restart: always
    depends_on:
      - pgsql
    networks:
      - bridge
      - pgnet
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5

  pgsql:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - pgnet
    volumes:
      - G:/Cache/pg/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  bridge:
    driver: bridge
  pgnet:
    external: false