spring:
  datasource:
    url: jdbc:postgresql://pgsql:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl