spring:
  datasource:
    url: jdbc:sqlite:G:/Cache/test.db
    username: pwd
    password: pwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.community.dialect.SQLiteDialect